#!/bin/bash
../../node_modules/typescript/bin/tsc --watch
return;
typescriptFile='aiToFolder.ts'
REDBOLD=$(tput setaf 1; tput bold)
GREENBOLD=$(tput setaf 2; tput bold)
YELLOWBOLD=$(tput setaf 3; tput bold)
# compileResult=$(../../node_modules/typescript/bin/tsc $typescriptFile)
# no args, rely on tsconfig.json for args
compileResult=$(../../node_modules/typescript/bin/tsc)

if [ $? -ne 0 ]; then  # $? is exit code from tsc transpiler
    echo compile $YELLOWBOLDS ERROR $(tput sgr0) from typescript tsc command: $compileResult
    exit
fi
echo $REDBOLD $typescriptFile $(tput sgr0) compiled!